### PR TITLE
Bump vllm to 0.6.6.post1

### PR DESCRIPTION
**Pull request by fialhocoelho**
[vLLM v0.6.5 has been released](https://github.com/vllm-project/vllm/releases/tag/v0.6.5). This PR updates the adapter to ensure compatibility with the latest release.

**TODO:** Additional testing is needed to verify if further updates are necessary.

### CODE REVIEW

**Comment by dtrifiro** [comment]
```
 ImportError: cannot import name 'iterate_with_cancellation' from 'vllm.utils' (/home/runner/.nox/tests-3-12/lib/python3.12/site-packages/vllm/utils.py)
 ```

**Comment by dtrifiro** [comment]
https://github.com/opendatahub-io/vllm/pull/265 has been merged as well

**Comment by dtrifiro** [comment]
Sync with 0.6.6 and 0.6.6.post1 has been merged as well: https://github.com/opendatahub-io/vllm/pull/279

**Comment by dtrifiro** [comment]
This is working with 0.6.6.post1, but failing with vllm-project/vllm@main. Gonna force merge and tackle the failures in another PR.

**Comment by dtrifiro** [comment]
Tests failure fixed in https://github.com/opendatahub-io/vllm-tgis-adapter/pull/202
